# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gomapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gomapp
          image: 394952106077.dkr.ecr.ap-northeast-2.amazonaws.com/gomapp:2
