apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment_patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: gomapp
  - path: namespace_patch.yaml
    target:
      kind: Namespace
      name: gomapp-prod
